In [1]:
import cv2
import os
import numpy as np
from PIL import Image,ImageOps
import pickle

In [2]:
BASE_DIR = os.path.abspath('')
data_dir = os.path.join(BASE_DIR, "recognizer_data")

In [3]:
face_cascade = cv2.CascadeClassifier('../data/haarcascade_frontalface_alt2.xml')

In [4]:
current_label = 0
labels = {}
y_labels = []
x_train = []

In [5]:
def get_max_img(imgs):
    max_i = 0;
    for i in range(imgs.shape[0]):
        if (imgs[i,2]*imgs[i,3]) > (imgs[max_i,2]*imgs[max_i,3]):
            max_i = i
    
    return [imgs[max_i,:]]

In [6]:
for root, dirs, files in os.walk(data_dir):
    for file in files:
        if file.endswith("png") or file.endswith("jpg"):
            path = os.path.join(root,file)
            label = os.path.basename(root)

            if label not in labels:
                labels[label] = current_label
                current_label += 1
            
            #Open image as gray and resize 
            image = cv2.imread(path)
            gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
            # resized_img = cv2.resize(gray, (240, 320), interpolation=cv2.INTER_AREA)
            final_image = np.array(gray,'uint8')

            faces = face_cascade.detectMultiScale(final_image,scaleFactor=1.01,minNeighbors=5)
            print(label)
            if (len(faces) > 1):
                faces = get_max_img(faces)
            for (x,y,w,h) in faces:
                face_crop = final_image[y:y+h, x:x+w]
                face_crop = cv2.resize(face_crop, (128, 128))
                x_train.append(face_crop)
                y_labels.append(labels[label])

alex
(371, 371)
alex
(136, 136)
alex
(342, 342)
alex
(92, 92)
alex
(48, 48)
jun
(91, 91)
jun
(116, 116)
jun
(148, 148)
jun
jun
(117, 117)
jun
(135, 135)
jun
(113, 113)
jun
(120, 120)
jun
(118, 118)
jun
jun
(105, 105)
jun
(103, 103)
jun
(91, 91)
jun
(89, 89)
medet
(250, 250)
medet
(119, 119)
medet
(360, 360)
medet
(219, 219)
medet
(408, 408)
medet
(113, 113)
medet
(347, 347)
medet
(190, 190)
medet
(313, 313)
medet
(49, 49)
medet
(201, 201)
medet
(119, 119)
medet
medet
(334, 334)
medet
(360, 360)
medet
(83, 83)
other
(48, 48)
other
(111, 111)
other
(98, 98)
other
(43, 43)
other
(45, 45)
other
other
(74, 74)
other
(66, 66)


In [7]:
with open("mask_face_labels.p",'wb') as f:
    pickle.dump(labels,f)

In [8]:
# def get_max_img(imgs):
#     max_i = 0;
#     for i in range(imgs.shape[0]):
#         if (imgs[i,2]*imgs[i,3]) > (imgs[max_i,2]*imgs[max_i,3]):
#             max_i = i
    
#     return [imgs[max_i,:]]
        

In [ ]:
# for root, dirs, files in os.walk(data_dir):
#     for file in files:
#         if file.endswith("png") or file.endswith("jpg"):
#             path = os.path.join(root,file)
#             label = os.path.basename(root)

#             if label not in labels:
#                 labels[label] = current_label
#                 current_label += 1
            
#             #Open image as gray and resize 
#             image = cv2.imread(path)
#             gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
#             final_image = np.array(gray,'uint8')
#             faces = np.array(face_cascade.detectMultiScale(final_image,scaleFactor=1.01,minNeighbors=5))
#             print(label)
#             if (faces.shape[0] > 1):
#                 faces = get_max_img(faces)
#             for (x,y,w,h) in faces:
#                 face_crop = final_image[y:y+h, x:x+w]
#                 print(face_crop.shape)
#                 face_crop = cv2.resize(face_crop, (128, 128))
#                 x_train.append(face_crop)
#                 y_labels.append(labels[label])

alex
[[143 144 139 ... 156 154 154]
 [148 155 140 ... 157 156 156]
 [141 157 148 ... 157 156 156]
 ...
 [151 152 153 ... 170 171 171]
 [146 147 148 ... 169 169 170]
 [144 145 145 ... 168 168 169]]
alex
[[157 153 141 ... 120 122 124]
 [154 155 145 ... 122 124 124]
 [151 157 149 ... 121 123 122]
 ...
 [165 166 167 ... 143 143 146]
 [164 165 167 ... 142 142 146]
 [164 165 168 ... 143 143 147]]
alex
[[ 87  81  85 ... 116 114 112]
 [ 90  87  84 ... 120 117 116]
 [ 91  93  88 ... 122 121 122]
 ...
 [155 154 156 ... 142 144 145]
 [154 151 150 ... 143 148 148]
 [155 152 152 ... 153 149 149]]
alex
[[ 47  40  38 ...  53  51 168]
 [ 41  35  37 ...  52  37 141]
 [ 37  34  38 ...  52  41 115]
 ...
 [148 179 210 ... 103 104 104]
 [107 112 132 ... 102 103 102]
 [126 110 101 ...  99 100  99]]
alex
[[ 88  77  76 ... 120 121 125]
 [ 78  66  72 ... 119 122 126]
 [ 72  74  76 ... 128 131 132]
 ...
 [174 175 175 ... 136 135 132]
 [173 174 175 ... 132 129 127]
 [172 172 174 ... 130 127 126]]


In [8]:
LBPHS = cv2.face.LBPHFaceRecognizer_create()
LBPHS.train(x_train, np.array(y_labels))
LBPHS.save("models/LBPHF.yml")

In [8]:
EigenFace=cv2.face.EigenFaceRecognizer_create()
EigenFace.train(x_train, np.array(y_labels))
EigenFace.write('models/Eigen.yml')